const RESTART_STATE = 'RESTART_STATE';
const SET_INTRO_STATE = 'SET_INTRO_STATE';
const SET_LOGIN_STATE = 'SET_LOGIN_STATE';
const SET_EXPIRED_SESSION = 'SET_EXPIRED_SESSION';

export { RESTART_STATE, SET_INTRO_STATE, SET_LOGIN_STATE, SET_EXPIRED_SESSION };